### ISSUE TITLE
gfan build issues on M1

### ISSUE THREAD

**Issue by abokeefe** [Macaulay2/homebrew-tap#100] opened 2021-07-02 15:04 UTC
I first ran into #92, and the workaround at the bottom + `brew postinstall libomp` got me past that error.
Now I am running into a ninja build error:
```
==> git clone https://github.com/Macaulay2/M2-emacs.git M2/Macaulay2/editors/emacs
==> cmake -GNinja -SM2 -BM2/BUILD/build-brew -DBUILD_NATIVE=OFF -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/bison;/opt/homebrew/opt/cmake;/opt/homebrew/opt/ninja;/opt/homebrew/opt/pkg
==> cmake --build M2/BUILD/build-brew --target M2-core M2-emacs
==> cmake --build M2/BUILD/build-brew --target install-packages
Last 15 lines from /Users/aokeefe/Library/Logs/Homebrew/macaulay2/04.cmake:
 -- making example results for "Example 3"                                   -- 1.10076 seconds elapsed
 -- making example results for "filteredComplex(ChainComplex)"               -- 0.860843 seconds elapsed
 -- making example results for "SpectralSequencePage _ List"                 -- 0.872207 seconds elapsed
 -- making example results for "tensor(RingMap,ChainComplex)"                -- 0.864891 seconds elapsed
 -- making example results for "Identifying anti-podal points of the two sphere" -- 1.44123 seconds elapsed
 -- making example results for "How to make filtered complexes from chain complex maps" -- 0.864011 seconds elapsed
 -- making example results for "spectralSequencePage"                        -- 1.32366 seconds elapsed
 -- making example results for "The trivial fibration over the sphere with fibers the sphere" -- 1.03549 seconds elapsed
 -- making example results for "Filtered complexes and simplicial complexes" -- 1.32513 seconds elapsed
 -- making example results for "SpectralSequence _ ZZ"                       -- 1.72374 seconds elapsed
 -- warning: found 109 documentation node(s) not listed as a subnode
 -- warning: missing node: maps between chain complexes cited by filteredComplex(List)
 -- warning: missing node: tensor(...,Constants=>...) cited by tensor(RingMap,ChainComplex)
 -- warning: 2 warning(s) occurred in documentation for package SpectralSequences
ninja: build stopped: subcommand failed.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
The Homebrew tap Macaulay2/tap/fflas-ffpack prevents Sage from building https://github.com/Macaulay2/homebrew-tap/issues/68
```
The very last lines are always a warning about 'documentation nodes not listed as a sub node', but the example results just above it are always different (the test examples are randomized).  I don't know if fflas-ffpack is what's failling, but issue #68 did not sound like this problem.

**Comment by huxw06** [comment] 2021-08-11 20:43
I am running into a similar error.

==> Installing macaulay2 from macaulay2/tap
==> Downloading https://github.com/Macaulay2/M2/archive/release-1.18.tar.gz
Already downloaded: /Users/huxw/Library/Caches/Homebrew/downloads/60b1fece6eabe5731625a73a84c9e7cf8bf8b5ec40040da0d67f29bbfaa9031f--M2-release-1.18.tar.gz
==> git clone https://github.com/Macaulay2/M2-emacs.git M2/Macaulay2/editors/emacs
==> cmake -GNinja -SM2 -BM2/BUILD/build-brew -DBUILD_NATIVE=OFF -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/bison;/opt/homebrew/opt/cmak
==> cmake --build M2/BUILD/build-brew --target M2-core M2-emacs
==> cmake --build M2/BUILD/build-brew --target install-packages
Last 15 lines from /Users/huxw/Library/Logs/Homebrew/macaulay2/04.cmake:
 -- making example results for "unirationalParametrization"                  -- 5.33039 seconds elapsed
 -- making example results for "associatedK3surface(SpecialGushelMukaiFourfold)" -- 8.76185 seconds elapsed
 -- making example results for "cycleClass"                                  -- 5.15918 seconds elapsed
 -- making example results for "< SpecialGushelMukaiFourfold"                -- 10.5341 seconds elapsed
 -- making example results for "discriminant(SpecialGushelMukaiFourfold)"    -- 6.14647 seconds elapsed
 -- making example results for "toGrass(EmbeddedProjectiveVariety)"          -- 3.74185 seconds elapsed
 -- making example results for "specialGushelMukaiFourfold(String,Ring)"     -- 5.20478 seconds elapsed
 -- making example results for "parameterCount(SpecialGushelMukaiFourfold)"  -- 8.4197 seconds elapsed
 -- making example results for "grassmannianHull"                            -- 5.91434 seconds elapsed
 -- making example results for "specialCubicFourfold(EmbeddedProjectiveVariety)" -- 2.22293 seconds elapsed
 -- making example results for "toGrass"                                     -- 4.15802 seconds elapsed
 -- making example results for "isAdmissible"                                -- 2.19491 seconds elapsed
 -- making example results for "detectCongruence(SpecialGushelMukaiFourfold,ZZ)" -- 10.5826 seconds elapsed
 -- warning: found 40 documentation node(s) not listed as a subnode
ninja: build stopped: subcommand failed.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
The Homebrew tap Macaulay2/tap/fflas-ffpack prevents Sage from building https://github.com/Macaulay2/homebrew-tap/issues/68

**Comment by mahrud** [comment] 2021-08-12 14:56
It would help if either of you could attach the full log from `/Users/[your username]/Library/Logs/Homebrew/macaulay2/04.cmake`. The warning about subnodes is not a fatal error, but CMake makes the example results in parallel, so the last package installed isn't necessarily the one that failed.

Also, example results aren't randomized, but the order in which they are installed may not be the same, so the last package you see installed will be different, even though the package that failed is likely the same.

It's strange to me that it's mentioning `fflas-ffpack` as a possible issue.

**Comment by huxw06** [comment] 2021-08-12 19:11
[CMakeError.log](https://github.com/Macaulay2/homebrew-tap/files/6977905/CMakeError.log)
[04.cmake.log](https://github.com/Macaulay2/homebrew-tap/files/6977914/04.cmake.log)

The logs are attached.

**Comment by mahrud** [comment] 2021-08-13 07:19
Is `gfan` working? Could you try running `brew test gfan` and reporting any errors?

**Comment by huxw06** [comment] 2021-08-13 14:24
I ran brew test gfan. An error occurred. The last lines are:

==> Testing macaulay2/tap/gfan
==> /opt/homebrew/Cellar/gfan/0.6.2_6/bin/gfan _version
==> /opt/homebrew/Cellar/gfan/0.6.2_6/bin/gfan _overintegers --groebnerFan
Error: macaulay2/tap/gfan: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: nil
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:218:in `assert_equal'
/opt/homebrew/Library/Homebrew/formula_assertions.rb:82:in `pipe_output'
/opt/homebrew/Library/Taps/macaulay2/homebrew-tap/Formula/gfan.rb:44:in `block in <class:Gfan>'
/opt/homebrew/Library/Homebrew/formula.rb:2049:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2048:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:939:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2047:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2300:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2041:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'

**Comment by mahrud** [comment] 2021-08-13 14:35
What happens if you just run:
```
echo "Q[x,y]\n{x^2-y^2,2*x}" | gfan _overintegers --groebnerFan
```
Perhaps try:
```
brew reinstall gfan
```
and try the test again.

**Comment by huxw06** [comment] 2021-08-13 19:53
The result of running 
echo "Q[x,y]\n{x^2-y^2,2*x}" | gfan _overintegers --groebnerFan
is
zsh: done                echo "Q[x,y]\n{x^2-y^2,2*x}" | 
zsh: segmentation fault  gfan _overintegers --groebnerFan

I tried brew reinstall gfan, and then brew test gfan, the result is still
==> Testing macaulay2/tap/gfan
==> /opt/homebrew/Cellar/gfan/0.6.2_6/bin/gfan _version
==> /opt/homebrew/Cellar/gfan/0.6.2_6/bin/gfan _overintegers --groebnerFan
Error: macaulay2/tap/gfan: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: nil
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:218:in `assert_equal'
/opt/homebrew/Library/Homebrew/formula_assertions.rb:82:in `pipe_output'
/opt/homebrew/Library/Taps/macaulay2/homebrew-tap/Formula/gfan.rb:44:in `block in <class:Gfan>'
/opt/homebrew/Library/Homebrew/formula.rb:2049:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2048:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:939:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2047:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2300:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2041:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'

**Comment by mahrud** [comment] 2021-08-13 21:54
Did `brew reinstall gfan` actually rebuild gfan? Try `brew reinstall -s gfan` perhaps. You can also try `brew reinstall -s cddlib@0.94`. If that doesn't help then I'm not sure what the issue could be.

You can put your code inside three backticks (`` ``` ``) so they are easier to read.

**Comment by huxw06** [comment] 2021-08-13 23:05
I think ```brew reinstall gfan``` did actually rebuild gfan. The last lines of the result is
```
==> make cddnoprefix=yes GMP_LINKOPTIONS=-L/opt/homebrew/opt/gmp/lib -lgmp GMP_INCLUDEOPTIONS=-I/opt/homebrew/opt/gmp/include OPTFLAGS=-O2 -DGM
==> make PREFIX=/opt/homebrew/Cellar/gfan/0.6.2_6 install
🍺  /opt/homebrew/Cellar/gfan/0.6.2_6: 60 files, 3.3MB, built in 23 seconds
```
I tried ```brew reinstall -s gfan```  and ```brew reinstall -s cddlib@0.94```. The last lines of the outputs are respectively
```
==> make cddnoprefix=yes GMP_LINKOPTIONS=-L/opt/homebrew/opt/gmp/lib -lgmp GMP_INCLUDEOPTIONS=-I/opt/homebrew/opt/gmp/include OPTFLAGS=-O2 -DGM
==> make PREFIX=/opt/homebrew/Cellar/gfan/0.6.2_6 install
🍺  /opt/homebrew/Cellar/gfan/0.6.2_6: 60 files, 3.3MB, built in 23 seconds
```
and
```
==> Reinstalling macaulay2/tap/cddlib 
==> ./configure --prefix=/opt/homebrew/Cellar/cddlib/0.94m
==> make install
🍺  /opt/homebrew/Cellar/cddlib/0.94m: 134 files, 4.4MB, built in 10 seconds
```
Then running ```brew test gfan``` the output seems identical to the previous one
```==> Testing macaulay2/tap/gfan
==> /opt/homebrew/Cellar/gfan/0.6.2_6/bin/gfan _version
==> /opt/homebrew/Cellar/gfan/0.6.2_6/bin/gfan _overintegers --groebnerFan
Error: macaulay2/tap/gfan: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: nil
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:218:in `assert_equal'
/opt/homebrew/Library/Homebrew/formula_assertions.rb:82:in `pipe_output'
/opt/homebrew/Library/Taps/macaulay2/homebrew-tap/Formula/gfan.rb:44:in `block in <class:Gfan>'
/opt/homebrew/Library/Homebrew/formula.rb:2049:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2048:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:939:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2047:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2300:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2041:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

Anyway, thanks a lot for your reply and suggestions!

**Comment by timduff35** [comment] 2021-08-18 16:31
I ran into a similar issue when building with cmake on a new MacBook pro. I built an M2 binary that meets most of my needs, except that gfanInterface doesn't work at all. Running

 ```echo "Q[x,y]\n{x^2-y^2,2*x}" | gfan _overintegers --groebnerFan```,

 I see the same segfault message reported by @huxw06 , after running the various suggested ```brew reinstall``` commands.

**Comment by mahrud** [comment] 2021-08-18 22:17
The issue is definitely with gfan on M1. I don't have any way to test this, so I'll leave it to someone with M1 to experiment with editing the formula for gfan and debugging the build problem:
https://github.com/Macaulay2/homebrew-tap/blob/bedd342aea19b3e66ad3e9e0462bb0f72fcb5741/Formula/gfan.rb#L33-L40
[This guide](https://docs.brew.sh/Formula-Cookbook#check-the-build-system) might be helpful.

**Comment by mahrud** [comment] 2021-11-19 21:58
I asked a friend of mine to test this on hi Apple M1 Pro, and it seems like `brew test gfan` succeeds now. I wonder if it was an M1 compiler problem that is now fixed. Can anyone try this again, ideally on an updated system?

**Comment by mahrud** [comment] 2021-11-28 07:11
A temporary workaround is to use
```
brew install macaulay2 --head
```
This should build Macaulay2 from the main branch on the repository, but not install any packages other than Macaulay2Doc, so that the missing gfan won't prevent it from being installed. Packages will be there on your system and you can load them the usual way, but they're not pre-installed, so the documentation might be a little slower.

**Comment by mahrud** [comment] 2021-12-11 23:07
gfan is now bottled for macOS 11.6 and I hear it is working on macOS 12, so I'll close this issue. If it persists for anyone, feel free to reopen or comment and I'll reopen.

**Closed by mahrud** 2021-12-11 23:07 UTC
Labels: help wanted

**Comment by huxw06** [comment] 2021-12-25 18:10
Thanks for the reminder. Just now I installed macaulay2 on M1 MacBook Pro
via brew.

Best regards,
Xiaowen

Mahrud Sayrafi ***@***.***> 于2021年12月12日周日 07:07写道：

**Comment by nobuki-takayama** [comment] 2021-12-27 05:16
Thanks for the update to the new cddlib. The new gfan works fine on my 
M1 MacBook Pro.

By the way, what C compiler do you use? Is it the clang on homebrew?

It seems that Apple clang 13.0 (based on llvm 12.0 
https://en.wikipedia.org/wiki/Xcode .
The latest llvm on homebrew is version 13) makes some optimizations so 
that
Boehm GC does not work properly. The trouble seems to be fixed on llvm 
13.

2021-12-12 08:07:

**Comment by mahrud** [comment] 2021-12-27 06:30
> By the way, what C compiler do you use? Is it the clang on homebrew?

Brew bottles are by default built using Xcode, unless the formula specifies that they fail with a certain compiler and another should be used.

> It seems that Apple clang 13.0 (based on llvm 12.0 https://en.wikipedia.org/wiki/Xcode . The latest llvm on homebrew is version 13) makes some optimizations so that Boehm GC does not work properly. The trouble seems to be fixed on llvm 13.

I'm not sure if I follow the problem, but it's important to separate Xcode and the clang coming from brew's llvm bottle, even when the version strings are the same. Both gcc and clang are symlinked to Xcode on macOS, but I'm fairly sure that's only superficial, and there isn't an actual clang compiler running behind Xcode.
