### ISSUE TITLE
Issue installing M2 on Apple Silicon

### ISSUE THREAD

**Issue by moorewf** [Macaulay2/homebrew-tap#67] opened 2021-02-16 19:47 UTC
I am having some difficulty installing M2 from the macaulay2 tap.  I have two installations of brew, namely an x86 one at /usr/local and a arm one at /opt/homebrew.  I suspect that this may have something to do with the issue, as others have been able to use this tap without problems.  Below are the outputs of the error in question, as well as brew config and brew doctor.

brew install $(brew deps --1 --include-build macaulay2/tap/M2):

```
==> Installing factory from macaulay2/tap
==> Downloading https://service.mathematik.uni-kl.de/ftp/pub/Math/Factory/factory-4.2.0.tar.gz
Already downloaded: /Users/moorewf/Library/Caches/Homebrew/downloads/b3441e1ccbdf47cb653fe65b39dbe6afa208dac7c00634d130e5b829716a4423--factory-4.2.0.tar.gz
==> autoreconf -vif
==> ./configure --disable-doxygen-doc --disable-omalloc --without-Singular --with-gmp=/opt/homebrew/opt/gmp --with-ntl=/opt/homebrew/opt/ntl --with-fl
Last 15 lines from /Users/moorewf/Library/Logs/Homebrew/factory/02.configure:
checking for m4... /usr/bin/m4
checking for bison... bison
checking size of long... (cached) 8
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether to use omalloc... no
checking   OMALLOC_INCLUDES?..... unset
checking   OMALLOC_LIBS?..... unset
checking whether libsingular_resources should be used... no
checking for atof in -lm... yes
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking for __gmpz_init in -lgmp... no
configure: error: GNU MP not found
```

brew config:
```
HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b9a6fd6791dab17e8b3137a2a73d311a70ffb05f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false
```

brew doctor:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/pkg-config
  /usr/local/bin/python3.9-config
  /usr/local/bin/python3-config

Warning: gettext files detected at a system prefix.
These files can cause compilation and link failures, especially if they
are compiled with improper architectures. Consider removing these files:
  /usr/local/lib/libgettextlib.dylib
  /usr/local/lib/libintl.dylib
  /usr/local/include/libintl.h
```

**Comment by mahrud** [comment] 2021-02-16 20:21
I'm confused about how you can have two paths in different architectures. How did you set that up? Which brew provided the outputs above? What does `brew --prefix` say?

I imagine the first step is to isolate the issue by removing `/usr/local` from your path. You probably need to do more than that, maybe try moving `/usr/local` to `/usr/local-tmp` to see if the ARM build works first.

I'm trying to think if there's any way for me to replicate this, but short of buying a mini mac I can't think of any options.

**Comment by moorewf** [comment] 2021-02-16 22:13
I made a copy of Terminal and told it to start using Rosetta 2.  Then running the brew install script recognized the architecture as x86 and it installs everything into /usr/local.  Then in the original Terminal I also ran the brew install script, which recognized the architecture as arm and it installed everything into /opt/homebrew.  These are the 'default' locations for homebrew under both architectures.

The commands in the original issue were created with the ARM brew install.  ARM brew is earlier on the path than the x86 install.  `brew --prefix` returns `/opt/homebrew`.

I tried moving /usr/local but the system complained, so I tried something more drastic.  I ended up wiping out both my homebrew installs and starting over, only installing the ARM one, and things seem to be working.  I can try to investigate further if you are interested.

**Comment by mahrud** [comment] 2021-02-17 07:46
I see, that makes sense. Glad to hear it's working with ARM alone. If you decide to set up a double architecture path again, we're need to look into why factory finds `gmp.h` but fails to find `__gmpz_init` in the library. In your email the full configure command that brew runs was this:
```
==> ./configure --disable-doxygen-doc --disable-omalloc --without-Singular --with-gmp=/opt/homebrew/opt/gmp --with-ntl=/opt/homebrew/opt/ntl --with-fl
```
I presume that's cut off, but that indicates that the gmp path is correctly set to `/opt/homebrew/opt/gmp`. So the next step would be to investigate what is going wrong.

A typical brew debugging step is to run something like this:
```
brew install --verbose --keep-tmp --build-bottle macaulay2/factory
```
Once this fails, there should be a line saying something along the lines of "kept temporary files in ...", then you can go to that directory and open `config.log` to see what went wrong.

Alternatively, you can try:
```
brew install --interactive --verbose --keep-tmp --build-bottle macaulay2/factory
```
This will download the necessary files and set up the build directory, but stop just before running any configure commands. So you would need to replicate the commands that it runs normally (`autoreconf`, `./configure ...`, etc.) and debug like a normal build.

My guess is that this is a factory bug, that somehow `/usr/local` is checked before the other paths regardless of your input (e.g. because `/usr/local` is hardcoded in factory, not because of its order in your path), and once it finds a x86 libgmp there that doesn't work, it errors out.

**Comment by mahrud** [comment] 2021-02-17 07:48
One more thing: if it is indeed the factory bug that I described, one solution that doesn't require removing `/usr/local` or removing that brew installation is to temporarily `brew unlink` the libraries in that prefix while you build in `/opt/homebrew`. I should have suggested this earlier before you removed this path, sorry!

**Comment by mahrud** [comment] 2021-06-23 03:51
Were you ever able to build M2 with two architectures available side by side?

**Comment by moorewf** [comment] 2021-06-23 12:37
Unfortunately, no.  I could do one or the other but not both.  I didn't try brew unlinking (as mentioned in your previous post) to get it to work, but that will probably do it as well.

**Comment by mahrud** [comment] 2021-12-11 23:11
It seems like `brew install macaulay2/tap/m2` is now working as intended on M1 machines, so I'll close this. I'll open a separate issue for bottling M2 for M1 machines.

**Closed by mahrud** 2021-12-11 23:11 UTC
