### ISSUE TITLE
Version 1.18-rc1_1 not functional and cannot be built from source (on Intel)

### ISSUE THREAD

**Issue by tom111** [Macaulay2/homebrew-tap#83] opened 2021-06-08 07:48 UTC
Hi,

I can't install/run M2 on my Intel Mac at the moment.  If I install the 1.18-rc1_1 bottle, then M2 does not run:
```
> M2
dyld: Symbol not found: __ZN3tbb4task13note_affinityEt
  Referenced from: /usr/local/bin/M2-binary
  Expected in: /usr/local/lib/libtbb.dylib
 in /usr/local/bin/M2-binary
/usr/local/bin/M2: line 2:  2067 Abort trap: 6           DYLD_LIBRARY_PATH=`dirname "$0"`/../lib/Macaulay2/lib:$DYLD_LIBRARY_PATH `dirname "$0"`/M2-binary "$@"
```

If I build from source it fails:

```
> brew install --build-from-source m2
[...]
[190/351] /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DNDEBUG -DOM_NDEBUG -DSING_NDEBUG -I../../Macaulay2/e -I../../Macaulay2/d -I../../Macaulay2/c -IMacaulay2/d -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 -I/usr/local/opt/mpsolve/include -I/usr/local/opt/mathicgb/include -I/usr/local/opt/mathic/include -I/usr/local/opt/memtailor/include -I/usr/local/opt/frobby/include -I/usr/local/opt/factory/include -I/usr/local/opt/flint/include -I/usr/local/opt/ntl/include -I/usr/local/opt/mpfi/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/bdw-gc/include -I/usr/local/opt/tbb/include -I/usr/local/opt/gdbm/include -I/usr/local/opt/libatomic_ops/include -isystem /usr/local/opt/gmp/include -isystem /usr/local/Cellar/givaro/4.1.1_4/include -isystem /usr/local/Cellar/fflas-ffpack/2.4.3_7/include -isystem /usr/local/opt/libomp/include -isystem /usr/local/opt/eigen/include/eigen3 -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wuninitialized -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/tmp/macaulay2-20210608-98361-jv9b4u/M2-release-1.18-rc1/M2/BUILD/build-brew/usr-host/include -I/tmp/macaulay2-20210608-98361-jv9b4u/M2-release-1.18-rc1/M2/include -I/tmp/macaulay2-20210608-98361-jv9b4u/M2-release-1.18-rc1/M2/BUILD/build-brew/include -Wall -Wextra -Wfatal-errors -Wcast-qual -Wno-unused-parameter -Wno-attributes -Wno-unused-command-line-argument -Wno-cast-qual -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-register -Wno-mismatched-tags -Wno-unused-variable -Xpreprocessor -fopenmp /usr/local/opt/libomp/lib/libomp.dylib -Xclang -std=gnu++17 -MD -MT Macaulay2/e/CMakeFiles/M2-engine.dir/interface/ring.cpp.o -MF Macaulay2/e/CMakeFiles/M2-engine.dir/interface/ring.cpp.o.d -o Macaulay2/e/CMakeFiles/M2-engine.dir/interface/ring.cpp.o -c ../../Macaulay2/e/interface/ring.cpp
[191/351] /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DNDEBUG -DOM_NDEBUG -DSING_NDEBUG -I../../Macaulay2/e -I../../Macaulay2/d -I../../Macaulay2/c -IMacaulay2/d -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 -I/usr/local/opt/mpsolve/include -I/usr/local/opt/mathicgb/include -I/usr/local/opt/mathic/include -I/usr/local/opt/memtailor/include -I/usr/local/opt/frobby/include -I/usr/local/opt/factory/include -I/usr/local/opt/flint/include -I/usr/local/opt/ntl/include -I/usr/local/opt/mpfi/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/bdw-gc/include -I/usr/local/opt/tbb/include -I/usr/local/opt/gdbm/include -I/usr/local/opt/libatomic_ops/include -isystem /usr/local/opt/gmp/include -isystem /usr/local/Cellar/givaro/4.1.1_4/include -isystem /usr/local/Cellar/fflas-ffpack/2.4.3_7/include -isystem /usr/local/opt/libomp/include -isystem /usr/local/opt/eigen/include/eigen3 -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wuninitialized -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/tmp/macaulay2-20210608-98361-jv9b4u/M2-release-1.18-rc1/M2/BUILD/build-brew/usr-host/include -I/tmp/macaulay2-20210608-98361-jv9b4u/M2-release-1.18-rc1/M2/include -I/tmp/macaulay2-20210608-98361-jv9b4u/M2-release-1.18-rc1/M2/BUILD/build-brew/include -Wall -Wextra -Wfatal-errors -Wcast-qual -Wno-unused-parameter -Wno-attributes -Wno-unused-command-line-argument -Wno-cast-qual -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-register -Wno-mismatched-tags -Wno-unused-variable -Xpreprocessor -fopenmp /usr/local/opt/libomp/lib/libomp.dylib -Xclang -std=gnu++17 -MD -MT Macaulay2/e/CMakeFiles/M2-engine.dir/interface/aring.cpp.o -MF Macaulay2/e/CMakeFiles/M2-engine.dir/interface/aring.cpp.o.d -o Macaulay2/e/CMakeFiles/M2-engine.dir/interface/aring.cpp.o -c ../../Macaulay2/e/interface/aring.cpp
ninja: build stopped: subcommand failed.
```

**Comment by mahrud** [comment] 2021-06-08 09:46
> I can't install/run M2 on my Intel Mac at the moment. If I install the 1.18-rc1_1 bottle, then M2 does not run:

See #82.

> If I build from source it fails:

Any idea what it failed on?

I've made several attempts on #80 to try to build better bottles, but don't have enough time to put on this for the next month. If you have any ideas for fixing it, please feel free to make a PR.

**Comment by mahrud** [comment] 2021-06-10 23:23
I've bottled v1.18, so I'll close this as a duplicate of #82 for now, but if you run into the error while building from source again feel free to reopen.

**Closed by mahrud** 2021-06-10 23:23 UTC
